name: TrustShield Compliance Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5 # Updated to v5
      with:
        python-version: '3.9'

    - name: Run Compliance Scanner
      run: |
        python scanner.py

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4 # FIX: v3 se v4 kar diya gaya hai
      with:
        name: compliance-report
        path: scan_results.json
